### ISSUE TITLE
[css-paint-api] Example of passing images to the paint worklet doesn't work in Chrome

### ISSUE THREAD

**Issue by gagyibenedek** [GoogleChromeLabs/houdini-samples#35]
[This example](https://drafts.css-houdini.org/css-paint-api/#example-2) does not work for me in the latest Chrome.  The image stays in the 'unloaded' state indefinitely. 
I'm not sure if this is a Chromium bug or  if the example is outdated.

**Comment by surma** [comment]
I don’t think Properties & Values API is implemented to that extend in Chrome yet.

**Comment by gagyibenedek** [comment]
Oh man, too bad :(

**Comment by surma** [comment]
Sooooon!
