### ISSUE TITLE
[css-typed-om] - Is animating registered <angle> properties not implemented yet in Chrome?

### ISSUE THREAD

**Issue by gagyibenedek** [GoogleChromeLabs/houdini-samples#39]
I was playing around with animating different custom properties, and found that while it works as expected for <length> and <percentage>, it fails for <angle>.
Here's a [codepen with and example](https://codepen.io/gben/pen/geyJeo).

Is this not implemented yet in Chrome, or am I misunderstanding/misusing something?

**Comment by malyw** [comment]
1) You have to update the demo, as the initialValue is required for any syntax, other than "*".
So update the https://codepen.io/gben/pen/geyJeo with the:
```
CSS.registerProperty({
      name: '--rot',
      syntax: '<angle>',
  initialValue: '0deg'
    });
```
2) The implementation is currently available in Chrome under the "Experimental Web Platform Features". The ideas when it's available OOB is here: https://twitter.com/malyw/status/984408643922726912

**Comment by gagyibenedek** [comment]
Facepalm.gif
I tried it, but forgot the '' from around the initialValue value.
Thanks for the quick answer!
