### ISSUE TITLE
[css-properties-values-api] Why does the draft use JS to define a new property?

### ISSUE THREAD

**Issue by gagyibenedek** [GoogleChromeLabs/houdini-samples#40]
I'm sure the writers had a good reason to do this, but I don't see why registering a new custom property has to be done from JS.
IMHO a syntax like
```
--custom-prop: * <length>;
```
has a few major advantages compared to
```
CSS.registerProperty({
    name: '--custom-prop',
    syntax: '<length>',
    initialValue: '*'
});
```
- Shorter, more readable;
- More natural environment. One of the cool things about typed custom properties is, that we can use them to animate stuff that was only possible using JS before. Using the alternative syntax that would be truly CSS only. Instead, we have to add a small piece of JS code to our project, that has no valuable info to the rest of the JS codebase. I know that separation of concerns  between CSS and JS has gotten a bit trickier since CSS-in-JS, but this syntax seems like a straight breach of this principle.
- It gives the possibility to declare non-global typed properties.

I guess a PostCSS plugin could make both of these syntaxes possible, I just don't understand the initial decision.
What am I missing?

**Comment by surma** [comment]
That’s something we want to explore in the future. We wanted to start with an imperative, more flexible JS-based API (similar to all other Houdini APIs). Once we have a good grasp on how these APIs get used we’ll look into an imperative way.
