### ISSUE TITLE
[css-properties-values-api] Why don't custom properties with types cascade?

### ISSUE THREAD

**Issue by gagyibenedek** [GoogleChromeLabs/houdini-samples#41]
Setting a value for a typed custom property on a container has no effect on its value for the elements inside. In other words the value doesn't cascade. Here's and [example ](https://codepen.io/gben/pen/WzqjwZ) demonstrating what I mean.
Is this by design? Are there other differences between "regular" and typed custom properties?

**Comment by surma** [comment]
That’s what the `inherits` options is for. If you do

```js
CSS.registerProperty({
  name: '--typed',
  syntax: '<color>',
  initialValue: 'blue',
  inherits: true
});
```

it will work as expected.
