### ISSUE TITLE
Worklet scope compared to Web Worker scope

### ISSUE THREAD

**Issue by YerkoPalma** [GoogleChromeLabs/houdini-samples#42]
Hi 👋 
Thanks for this module! Your examples have been very helpful. 
Now, I'm confused about the scope of Worklets, the posts about worklets say they are like a _lightweight web wroker_, so, because of some of their similarities I though I could use the sames APIs availaible for workers, but that isn't true.

My specific use case, is that I was trying to draw an Image from a paintWorklet.

Here is the code of my worklet 

```js
registerPaint('tiles', class {
  paint (ctx, geom, properties) {
    fetch('https://mdn.mozillademos.org/files/5397/rhino.jpg')
    .then(response => response.blob())
    .then(blob => createImageBitmap(blob))
    .then(bitmap => {
      ctx.drawImage(bitmap, 33, 71, 104, 124, 21, 20, 87, 104)
    })
  }
})
```

This throws that fetch is not defined

![image](https://user-images.githubusercontent.com/5105812/40994664-cc587f02-68ca-11e8-8d13-b870c15a0f03.png)

So the question is, what APIs are availaible from a paintworklet? or any worklet?

**Comment by surma** [comment]
they are “like” a lightweight web worker in the sense that they are a separate scope and (potentially) thread. But they have almost no APIs exposed to them. 

If you need to fetch an image for a paint worklet, you need to do that on the main thread and pass the image via custom properties.

**Comment by surma** [comment]
Yes, you can in combination with Typed OM and Properties & Values API, although none of these are currently fully implemented in Chrome to support images as far as I know.

**Comment by YerkoPalma** [comment]
Oh I see, just found [this example](https://www.w3.org/TR/css-paint-api-1/#example-2) about image loading. Hope this get implemented soon :) thanks again
