### ISSUE TITLE
Parallax working with Experimental features disabled

### ISSUE THREAD

**Issue by IOIIOOIO** [GoogleChromeLabs/houdini-samples#46]
The parallax demo at the link only seems to work if I disable Experimental Web Platform features.

https://googlechromelabs.github.io/houdini-samples/animation-worklet/parallax-scrolling/

Chrome Version: Version 66.0.3359.181

**Comment by surma** [comment]
All of the Animation Worklet demos require Canary. We are working on fixing the polyfill.
