### ISSUE TITLE
Twitter demo not working

### ISSUE THREAD

**Issue by IOIIOOIO** [GoogleChromeLabs/houdini-samples#47]
The Twitter demo at the link doesn't seem to be having the expected effect even with Experimental Web Platform features enabled. The Profile picture just continues scrolling out of view.

https://googlechromelabs.github.io/houdini-samples/animation-worklet/twitter-header/

Chrome Version: Version 66.0.3359.181

**Comment by surma** [comment]
Animation Worklet has not landed in stable (not even behind a flag). You need Canary.
